### ISSUE TITLE
Create a Nextjs app

### ISSUE THREAD

**Issue by mbuckingham** [mbuckingham/adhd-math-frontend#1]
- Create a nextjs app.
- Remove useless boilerplate. 
- Make sure to use Typescript

**Comment by Nat-crit20** [comment]
I created the Nextjs app and made sure to use typescript. I had an issue with the npm run start not working because of some Nodejs error:

 "You are using Node.js 18.9.0. For Next.js, Node.js version >= v18.17.0 is required." 

Nothing I did to fix the issue worked, but I got it to work by installing yarn and using yarn dev, which is why there is a yarn.lock file.
